export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Experience } from './experience/Experience'
export { default as Projects } from './projects/Projects'
export { default as Contact } from './contact/Contact'
